######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 30 17:19:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += driver.h piranha.h playback.h setup.h
SOURCES += driver.cpp main.cpp piranha.cpp playback.cpp setup.cpp
